version: '3.8'

services:
  # База данных PostgreSQL для Zabbix
  postgres-server:
    image: postgres:15-alpine
    container_name: zabbix-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-net
    ports:
      - "5432:5432"

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server-dev
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      ZBX_JAVAGATEWAY_ENABLE: "true"
      ZBX_JAVAGATEWAYPORT: 10052
      ZBX_DEBUGLEVEL: 3
      ZBX_CACHESIZE: 64M
      ZBX_HISTORYCACHESIZE: 32M
      ZBX_HISTORYINDEXCACHESIZE: 8M
      ZBX_TRENDCACHESIZE: 8M
      ZBX_VALUECACHESIZE: 32M
    volumes:
      - zabbix_server_data:/var/lib/zabbix
      - zabbix_server_enc:/var/lib/zabbix/enc
      - zabbix_server_ssh_keys:/var/lib/zabbix/ssh_keys
      - zabbix_server_ssl_certs:/var/lib/zabbix/ssl/certs
      - zabbix_server_ssl_keys:/var/lib/zabbix/ssl/keys
      - zabbix_server_ssl_ca:/var/lib/zabbix/ssl/ssl_ca
    networks:
      - zabbix-net
    ports:
      - "10051:10051"
    depends_on:
      - postgres-server
      - zabbix-java-gateway

  # Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web-dev
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_TZ: Europe/Moscow
      ZBX_SERVER_NAME: "Zabbix Development"
      NGINX_CLIENT_MAX_BODY_SIZE: 16m
      ZBX_BASEURL: /zabbix
    volumes:
      - zabbix_web_ssl:/etc/ssl/nginx
    networks:
      - zabbix-net
    # Убираем внешние порты, доступ только через nginx
    expose:
      - "8080"
      - "8443"
    depends_on:
      - postgres-server
      - zabbix-server

  # Nginx прокси для Zabbix
  nginx:
    image: nginx:alpine
    container_name: zabbix-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - zabbix-net
    depends_on:
      - zabbix-web
      - grafana

  # Zabbix Java Gateway
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.4-latest
    container_name: zabbix-java-gateway-dev
    restart: unless-stopped
    environment:
      ZBX_DEBUGLEVEL: info
      ZBX_TIMEOUT: 3
    networks:
      - zabbix-net
    ports:
      - "10052:10052"

  # Zabbix Agent
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: zabbix-agent-dev
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: "Zabbix Development Server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_DEBUGLEVEL: 3
      ZBX_PASSIVE_ALLOW: "true"
      ZBX_ACTIVE_ALLOW: "true"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
    networks:
      - zabbix-net
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-server
    privileged: true
    pid: "host"

  # Grafana для визуализации данных из Zabbix
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dev
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_PLUGINS_PREINSTALL: alexanderzobnin-zabbix-app
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: alexanderzobnin-zabbix-datasource
      GF_SERVER_ROOT_URL: "http://localhost/grafana/"
      GF_APP_URL: "http://localhost/grafana/"
      GF_SERVER_DOMAIN: "localhost"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
      GF_SERVER_HTTP_PORT: 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    networks:
      - zabbix-net
    ports:
      - "3000:3000"
    depends_on:
      - zabbix-server
      - zabbix-web

volumes:
  postgres_data:
  zabbix_server_data:
  zabbix_server_enc:
  zabbix_server_ssh_keys:
  zabbix_server_ssl_certs:
  zabbix_server_ssl_keys:
  zabbix_server_ssl_ca:
  zabbix_web_ssl:
  nginx_logs:
  grafana_data:
  grafana_logs:

networks:
  zabbix-net:
    driver: bridge